version: "3"

networks:
  database_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  mysql-db: {}
  local_node_modules: {}

services:
  db:
    build:
      context: .
      dockerfile: ./compose/local/db/Dockerfile
    # volumes:
    #   - mysql-db:/var/lib/mysql
    networks:
      - database_network
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'pruebaTyba'
      MYSQL_USER: 'userTest'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  app:
    build:
      context: .
      dockerfile: ./compose/local/app/Dockerfile
    volumes:
      - ./src:/usr/src
      - local_node_modules:/usr/src/node_modules
    networks:
      - database_network
      - nginx_network
    depends_on:
      - db

  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./config/local/nginx/conf.d:/etc/nginx/conf.d
    links:
      - app
    networks:
      - nginx_network

